# Generated by Django 3.0.7 on 2020-06-13 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20200610_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategories',
            name='category',
        ),
        migrations.RemoveField(
            model_name='topics',
            name='category',
        ),
        migrations.RemoveField(
            model_name='topics',
            name='sub_cat',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='SubCategories',
        ),
    ]
