# Generated by Django 3.0.7 on 2020-06-13 15:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20200613_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribers',
            name='is_liked',
        ),
        migrations.CreateModel(
            name='IsLikedTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_liked', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_is_liked', to='forum.Topics')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_likes_topic', to='forum.Users')),
            ],
            options={
                'db_table': 'is_liked_topic',
            },
        ),
    ]
