# Generated by Django 3.0.7 on 2020-06-15 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_remove_topics_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='islikedtopic',
            name='is_liked',
        ),
    ]
