# Generated by Django 3.0.7 on 2020-06-21 03:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_auto_20200621_0240'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsLikedComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_is_liked', to='forum.Comment')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_is_commented', to='forum.Topics')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_likes_comment', to='forum.Users')),
            ],
            options={
                'db_table': 'is_liked_comment',
            },
        ),
    ]
